export const MAX_UNATTACHED_PAYMENT_PROOFS_PER_CUSTOMER = 3;
export const MAX_ATTACHED_PAYMENT_PROOFS_PER_ORDER = 12;
export const MAX_ATTACHED_PAYMENT_PROOFS_PER_CUSTOMER = 24;
export const MAX_ATTACHED_PAYMENT_PROOF_BYTES_PER_CUSTOMER = 240 * 1024 * 1024;
export const MAX_ACTIVE_PENDING_PROOF_ORDERS_PER_CUSTOMER = 3;
export const MAX_PAYMENT_PROOF_DB_GC_BATCH = 100;
export const MAX_PAYMENT_PROOF_LEGACY_SCAN_BATCH = 250;
export const MAX_PAYMENT_PROOF_LEGACY_DELETE_BATCH = 50;
